version: 0.2
env:
  variables:
    LT_USERNAME: "anubhas"
    LT_ACCESS_KEY: "JvGShZ2Bm8RdgmGFbbx4ZtbOb6DeQ8nqSvtHDZdDY7PzqaZMTq"
phases:
  install:
    runtime-versions:
      nodejs: 10
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - mvn install
  build:
    commands:
      - echo Build started on `date`
      - cd conf
      - mvn test -D suite=android_parallel.xml 
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
discard-paths: yes
